#-----------------------------
# GamemodeChanger Config Files
#-----------------------------

#ゲームモードを変更した際に表示されるメッセージ
#カラーコードが使えます。
Gamemode:
  Survival: "&aゲームモードを &lサバイバル &r&aに変更しました。"
  Creative: "&aゲームモードを &lクリエイティブ &r&aに変更しました。"
  Adventure: "&aゲームモードを &lアドベンチャー &r&aに変更しました。"
  Spectator: "&aゲームモードを &lスペクテイター &r&aに変更しました。"

# アップデートの通知
#サーバ起動時(リロード時)にサーバと通信してバージョンを確認します。
Update: true
